InfoCardComponentsの作成(#61)
NUTFes/NUTFES-Account pull request #76
Opened 2023-06-12 09:39 UTC by ryuseifujisaki

## 対応 Issue

resolve #61 

## 概要

InfoCardComponentsを作成
- frontend/src/components/InfoCard/InfoCard.tsxにComponentsを定義
- frontend/src/pages/personal-info/index.tsxにPageを作成

## テスト項目

- [ ] `http://localhost:3000/personal-info`で以下のスクリーンショットのように表示されているか
- [ ] コードで不十分なところはないか
- [ ] デザインが問題ないか

## URL・スクリーンショット

- [http://localhost:3000/personal-info](http://localhost:3000/personal-info)

![image](https://github.com/NUTFes/NUTFES-Account/assets/50622120/f5127b25-1213-4520-aa4c-bd030c520e71)

## 備考

2023-06-12 10:32 UTC, TsubasaOura requested changes
いくつか変更点があります！
よろしくおねがいいたします！

2023-06-12 10:32 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +}
```suggestion
interface Props {
  data : {
    title: string;
    description: string;
    table: {
      item: string;
      value: string;
      link: string;
    }[];
  }
}
```

2023-06-12 10:32 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +}
dataを読んで来るだけにしたい！

2023-06-12 10:32 UTC, TsubasaOura commented on frontend/src/pages/personal-info/index.tsx
> +      <InfoCard title={infoData.title} description={infoData.description} table={infoData.table}/>
```suggestion
      <InfoCard data={infoData}/>
```

2023-06-12 10:32 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +                  <Link href={row.link} color="inherit" underline="none" >＞</Link>
```suggestion
                  <Link href={row.link} color="inherit" underline="none" ><ArrowForwardIosIcon /></Link>
```

2023-06-12 10:33 UTC, TsubasaOura commented on frontend/src/pages/personal-info/index.tsx
> +      <InfoCard title={infoData.title} description={infoData.description} table={infoData.table}/>
＞はふぉんとによって表示が変わるのでアイコン使いたい

2023-06-12 10:33 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +                  <Link href={row.link} color="inherit" underline="none" >＞</Link>
＞はフォントによって表示が変わるのでアイコン使いたい

2023-06-12 10:50 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +      <CardContent>
```suggestion
    <Paper variant="outlined"  sx={{minWidth:723, maxWidth: 1023}}>
```
クリック要素が入らないのでPaperがよき

2023-06-12 10:50 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +                <TableCell align="right">
```suggestion
             <DataGrid
        rows={rows}
        columns={columns}
      />
```

https://mui.com/material-ui/react-table/#basic-table

これ使ってみても良いかも

どっちにしてもホバーすると暗くなるのはお願いします

2023-06-13 14:48 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +      <CardContent>
InfoCard自体にクリック要素はないので

- Paperコンポーネント使用
- 影はなし

でお願いします

2023-06-13 14:52 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +                  <Link href={row.link} color="inherit" underline="none" >＞</Link>
<ArrowForwardIosIcon />と<KeyboardArrowRightIcon/>は別物なので前者でお願いします。
後者はコントロール用のボタンに使うようなアイコンになってます！

LinkがIconにしか適応されていないので、行そのものに適応させて欲しいです！
そのためにもDataGridつかうのがよきかもです！

2023-06-13 15:03 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +                  <Link href={row.link} color="inherit" underline="none" >＞</Link>
追記！

参考にしてもらってるmyaccount.google.comでは矢印に
'@mui/icons-material/ChevronRight'使ってました！

これでお願いします！！

2023-06-13 15:04 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +                <TableCell align="right">
暗くなったホバーにマージンがあるとちょっとキモさあるのでマージンをなくしたい
CardContentのせいだと思うのでPaper使ってください！

2023-06-13 15:11 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +        </Typography>
細かいですが文字と文字の間に隙間をあけてください
myaccount.google.com では 8pxの隙間があります。

また、myaccont.google.comではtitleとdescriptionは一つのdivタグで囲まれているのでそれも参考にすると良いです。

2023-06-13 15:12 UTC, TsubasaOura commented
myaccount.google.com の完全クローンを作る勢いでOKです

2023-06-16 15:59 UTC, TsubasaOura requested changes
よろしくおねがいいたします！！！

2023-06-16 15:59 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +function InfoCard({ data }: Props) {
```suggestion
const InfoCard = ({ data }: Props) => {

const handleClick = (link: string) => {
  try {
    Router.push(link);
  } catch(err){
    console.error("Not Exist Page")
  }
}

```

2023-06-16 15:59 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +function InfoCard({ data }: Props) {
こういうふうにかけるかも？

2023-06-16 15:59 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +      <CardContent>
ここがまだ対応されてないかも？
variant="outlined"
がおすすめです

2023-06-16 15:59 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +        <Table>
Table要素の中のTableBodyの上にBoxでタイトルと説明入れるとホバー時うまくいく説あるかも

2023-06-16 16:09 UTC, ryuseifujisaki commented on frontend/src/components/InfoCard/InfoCard.tsx
> +        <Table>
それはなぜや？

2023-06-16 16:48 UTC, TsubasaOura requested changes

2023-06-16 16:48 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +      <Box sx={{minWidth:680, pt: 3, px: 2, pb: 1}}>
ｍinWidthはスマホ対応の障害になるのでなしでOK

2023-06-16 16:48 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +      <Box sx={{minWidth:680, pt: 3, px: 2, pb: 1}}>
いくつかあるので他も同様にお願いします

2023-06-16 16:48 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +              <TableCell align="left" sx={{color: "text.secondary"}} >{row.value}</TableCell>
myaccount.google.comでは600px以下でitemと同じ行に改行して表示されるので余力があれば実現してみて欲しい

2023-06-16 16:48 UTC, TsubasaOura commented on frontend/src/components/InfoCard/index.ts
> +export { default as InfoCard} from './InfoCard'
細かいけど俺のVscodeではInfoCardの隣にSpaceがないから怒られた

2023-06-16 16:48 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +            {data.description.split('\n').map((t, index)=> (<span key={index}>{t}<br /></span>))}
俺のVScodeではここがFormatされた何でやろか。
あと、今のDevelopリベースするとコミット時に勝手に整形はいるのでおすすめ！

2023-06-16 18:14 UTC, TsubasaOura requested changes

2023-06-16 18:14 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +      Router.push(link);
```suggestion
const InfoCard = ({ data }: Props) => {
   const router = useRouter();
   const handleClick = (link: string) => {
     router.push(link).catch((error) => {
       console.error(error);
     });
   };
```

2023-06-16 18:14 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +      Router.push(link);
アロー関数系式で書くのがモダン
あと、Try・Catchでやる方法もいいと思うんだけど
なんかLintに怒られたので上記の方法がよさそうです

2023-06-16 19:41 UTC, TsubasaOura requested changes

2023-06-16 19:41 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +          </span>
```suggestion
          <Typography
            variant="body2"
            color="text.secondary"
            sx={{ pt: 1, whiteSpace: "pre-wrap" }}
            className="text"
          >
            {data.description}
          </Typography>
```

これででける

2023-06-16 19:41 UTC, TsubasaOura commented on frontend/src/pages/personal-info/index.tsx
> +  "description": `自宅と勤務先の住所は、Google サービスの利便性をパーソナライズするとともに、関連性の高い広告を表示するために使用されます。これらの住所はあなたにだけ表示されます。\nまた、上記の住所とは別に、Google プロフィールに住所を追加することもできます。他のユーザーに自分のプロフィールの住所を公開するかどうかは自分で選択できます。`,
バッククウォートから始めれば`\n`いらない

2023-06-16 19:41 UTC, TsubasaOura commented on frontend/src/pages/personal-info/index.tsx
> +  "description": `自宅と勤務先の住所は、Google サービスの利便性をパーソナライズするとともに、関連性の高い広告を表示するために使用されます。これらの住所はあなたにだけ表示されます。\nまた、上記の住所とは別に、Google プロフィールに住所を追加することもできます。他のユーザーに自分のプロフィールの住所を公開するかどうかは自分で選択できます。`,
直接改行可能

2023-06-16 19:41 UTC, TsubasaOura commented on frontend/src/components/InfoCard/InfoCard.tsx
> +        <Typography variant="body2" color="text.secondary" sx={{pt: 1}}>
```suggestion
        {data.description ? (<Typography variant="body2" color="text.secondary" sx={{pt: 1}}>
```
デスクリプションがない時用処理を三項演算子で書いときたい

2023-06-17 03:43 UTC, ryuseifujisaki reviewed
俺もPrettier導入したら同じ結果になった

2023-06-17 06:06 UTC, TsubasaOura approved these changes

2023-06-17 06:06 UTC, merged