DetailLayoutno
NUTFes/NUTFES-Account pull request #84
Opened 2023-06-20 16:32 UTC by ryuseifujisaki

## 対応 Issue

resolve #0

## 概要

## テスト項目

- [ ] 
- [ ] 

## URL・スクリーンショット

- 
- 

## 備考

2023-06-21 08:49 UTC, TsubasaOura requested changes

2023-06-21 08:49 UTC, TsubasaOura commented on frontend/src/components/layout/DetailLayout.tsx
> +  const backPage = () => {
next routerなら戻る関数がありそう

2023-06-21 08:49 UTC, TsubasaOura commented on frontend/src/components/layout/DetailLayout.tsx
> +          <div className="w-3/5 w-[576px] text-3xl">{data.title}</div>
ここはTypographyで良さそう

2023-06-21 08:49 UTC, TsubasaOura commented on frontend/src/components/layout/DetailLayout.tsx
> +  data: {
今回はdataじゃなくてもいいかも。前回データにしたかったのは、personal-infoページにPersonalInfoCardを複数配置するから、data配列をmap出来るメリットがあった。

2023-06-21 08:49 UTC, TsubasaOura commented on frontend/src/components/layout/DetailLayout.tsx
> +      <div className="flex snap-y flex-col items-center justify-center pt-20">
これはMUIコンポーネントの変わり的ならやつかな？

いまいまいがレイアウトにはTailwindと言ってたけどそういう意味ではないはず。

LayoutコンポーネントにはTailwindのみを使用しなさいではなく、コンポーネントの配置にTailwindを使用しましょうの意味なので、DetailLayoutだからといってMUI使っちゃだめではないです

2023-06-21 08:49 UTC, TsubasaOura commented on frontend/src/components/layout/DetailLayout.tsx
> +          <button type="button" className="mr-1 h-12 w-12" onClick={backPage}>
MUIにありそう

2023-06-21 08:49 UTC, TsubasaOura commented
時間が取れず、ローカルで確認はできてませんが、コメントしておきました！

2023-06-21 08:51 UTC, TsubasaOura commented on frontend/src/components/layout/DetailLayout.tsx
> +  data: {
これはどっちが良いか微妙なのではんだんできないない

2023-06-22 05:44 UTC, ryuseifujisaki commented on frontend/src/components/layout/DetailLayout.tsx
> +      <div className="flex snap-y flex-col items-center justify-center pt-20">
```
      <div className="flex snap-y flex-col items-center justify-center pt-20">
```
ここに関しては細かいlayoutの調整がMUIだとどうしてもできなくて、tailwind使ったんよな〜

2023-06-22 05:44 UTC, ryuseifujisaki commented on frontend/src/components/layout/DetailLayout.tsx
> +          <div className="w-3/5 w-[576px] text-3xl">{data.title}</div>
それはそう

2023-06-22 05:44 UTC, ryuseifujisaki commented on frontend/src/components/layout/DetailLayout.tsx
> +  data: {
なるほど。
dataだと、Domを見た時に何が入ってくるか分かりにくいので、普通に分けた方が良さそう

2023-06-22 05:45 UTC, TsubasaOura commented on frontend/src/components/layout/DetailLayout.tsx
> +      <div className="flex snap-y flex-col items-center justify-center pt-20">
それならよさ

2023-06-22 13:48 UTC, TsubasaOura commented
立ち上げて確認しました！

- フォントサイズが違う
  - 30pxではなく28pxです
  - また、あるブレークポイントで24pxになります
- ヘッダーのラインがブレークポイントできえる処理がありません
- 画面を小さくしていった時のバックボタンの動き方がｍyaccount.google.comと差異がある
  - 縮めていくとある点で矢印は動かなくなるのが正しいです

2023-06-22 13:53 UTC, TsubasaOura commented
- childrenはvariant=outrinedのPaperで囲いたい。あとこれもブレークポイントで表示非表示を制御したい。

2023-06-22 13:55 UTC, TsubasaOura commented
minWidthがあればこうはならないはず
横幅ぴったり
![image](https://github.com/NUTFes/NUTFES-Account/assets/46074208/ab1ab4e0-d856-4f18-9a5d-24f76f15f628)

2023-06-23 15:22 UTC, ryuseifujisaki commented on frontend/src/components/layout/DetailLayout.tsx
> +  const backPage = () => {
router.back使っても良さそうだけど、直リンクで来られて戻るボタン押されたら、変なところに戻るのでrouter.pushがいいかもと思った。

2023-06-24 16:58 UTC, TsubasaOura commented on frontend/src/components/layout/DetailLayout.tsx
> +  const backPage = () => {
なるほどそれはあるな

2023-06-24 17:03 UTC, TsubasaOura commented on frontend/src/components/layout/DetailLayout.tsx
> +  const backPage = () => {
戻るはrouter.pushでいきましょう

2023-06-25 11:09 UTC, TsubasaOura approved these changes

2023-06-25 12:21 UTC, merged