Sideタブ作成
NUTFes/NUTFES-Account pull request #85
Opened 2023-06-21 01:02 UTC by TsubasaOura

## 対応 Issue

resolve #0

## 概要

## テスト項目

- [ ] 
- [ ] 

## URL・スクリーンショット

- 
- 

## 備考

2023-06-22 17:00 UTC, imaimai17468 requested changes
ざっとレビューしました！

2023-06-22 17:00 UTC, imaimai17468 commented on frontend/src/components/common/SideTab.tsx
> +  ];
constantな要素はグローバルな領域に宣言した方が良いです
constantsディレクトリとかを作って、そこに定義するのもあり

```suggestion
  const TABS = [
    {
      key: "home",
      name: "ホーム",
      icon: <AccountCircle />,
      url: "/",
    },
    {
      key: "personal-info",
      name: "個人情報",
      icon: <ListAlt />,
      url: "/personal-info",
    },
    {
      key: "qrcode",
      name: "学祭QRコード",
      icon: <QrCode />,
      url: "/qrcode",
    },
  ];
const SideTab = () => {
  const router = useRouter();
  const handleClick = (link: string) => {
    router.push(link).catch((error) => {
      console.error(error);
    });
  };
```

2023-06-22 17:00 UTC, imaimai17468 commented on frontend/src/components/common/SideTab.tsx
> +              borderBottomRightRadius: 22,
[note] 本家を見に行くと、border-radiusが50pxだったので一応

```suggestion
              borderTopRightRadius: 25,
              borderBottomRightRadius: 25,
```

2023-06-22 17:00 UTC, imaimai17468 commented on frontend/src/components/common/SideTab.tsx
> +          }}
具体的にwidthとheightを指定せずに、paddingやmergin、flexで位置とサイズの調整をして、本体の幅は可変の方がいいと思います（宗教かも）
widthとheightを指定して、他要素と齟齬があると、UIが食い違う場合があります

2023-06-22 17:00 UTC, imaimai17468 commented on frontend/src/components/common/SideTab.tsx
> +              }}
これも

2023-06-22 17:00 UTC, imaimai17468 commented on frontend/src/components/common/SideTab.tsx
> +            }}
クリックするとfocusが外れてしまう場合は、もう条件によってスタイルを出し入れするのがいいです
ちょっと汚いですけど

```suggestion
sx={
              router.pathname === tab.url
                ? {
                    borderTopRightRadius: 25,
                    borderBottomRightRadius: 25,
                    backgroundColor: "#E8F0FE",
                    color: "#1967D2",
                    "& .MuiListItemIcon-root": {
                      color: "#1967D2",
                    },
                    "&:hover": {
                      backgroundColor: "#E8F0FE",
                    },
                  }
                : {
                    borderTopRightRadius: 25,
                    borderBottomRightRadius: 25,
                    color: "text.secondary",
                  }
            }
```

2023-06-25 04:46 UTC, TsubasaOura commented on frontend/src/components/common/SideTab.tsx
> +  ];
constants使うのはアリだな！
SideTabの内容をHead Tabでも使用しようとしてたのでちょうど良いかも
FinanSu参考にしてみます！

2023-06-25 04:48 UTC, TsubasaOura commented on frontend/src/components/common/SideTab.tsx
> +              borderBottomRightRadius: 22,
あれこれはまじか
Tabの高さが44と思ったからこう設定したんだけどそもそもTabの高さが間違ってる説あるな

2023-06-25 04:50 UTC, TsubasaOura commented on frontend/src/components/common/SideTab.tsx
> +          }}
これに関してはTabのサイズを一定にしておきたいっていう気持ちがあるけど、
その場合もMerginとかで設定した方がいいんかな。
Googleアカウントではどんな時でもTabサイズ一定で、表示しきれないってなった時に非表示って感じだ

2023-06-25 04:50 UTC, TsubasaOura commented on frontend/src/components/common/SideTab.tsx
> +            }}
これ良いね

2023-06-25 06:41 UTC, TsubasaOura commented
@imaimai17468 ご確認の程よろしくお願いいたします
https://github.com/NUTFes/NUTFES-Account/pull/85#discussion_r1241029706

2023-06-25 17:45 UTC, imaimai17468 requested changes
レビュー追加しました！

2023-06-25 17:45 UTC, imaimai17468 commented on frontend/src/constants/tabs.tsx
> +];
[note] UPPER_CASEを用いることでconstantsだと強調できます

[very small note] 
できれば`as const`型アサーションを使うことで、リテラル型であることを強調したいですが、TabItemとしての形を保守したい場合は現状のままで大丈夫です
参考：https://zenn.dev/yumemi_inc/articles/js-front-constants-a1fb3c49eb1199#%E3%81%93%E3%81%AE%E8%A8%98%E4%BA%8B%E3%81%A7%E6%B1%82%E3%82%81%E3%82%8B%E3%80%8C%E4%BF%9D%E5%AE%88%E6%80%A7%E3%80%8D
参考：https://typescriptbook.jp/reference/values-types-variables/type-assertion-as

```suggestion
export const TABS = [
  {
    key: "home",
    name: "ホーム",
    icon: <AccountCircle />,
    href: "/",
  },
  {
    key: "personalInfo",
    name: "個人情報",
    icon: <ListAlt />,
    href: "/personal-info",
  },
  {
    key: "qrcode",
    name: "学祭QRコード",
    icon: <QrCode />,
    href: "/qrcode",
  },
] as const;
```

2023-06-25 17:45 UTC, imaimai17468 commented on frontend/src/components/common/SideTab.tsx
> +          }}
widthとheightを指定した場合、iconやnameが絶対にListItemからはみ出さないことが保証されてるなら指定していいです（それでも非推奨なところがあるかも）
myaccountの方も、cmd+shift+cで確認すると、widthとheightを指定していないと思います
iconやnameのサイズを全て調整しておき、一定のpaddingを各listに当てることで一定のサイズにしています
widthを一定にしたいなら、sidetabの親要素で指定して、小要素のsidetabはその100%をwidthとして指定し、レイアウトをflexで管理した方が安全だと思います

2023-06-26 15:50 UTC, TsubasaOura commented on frontend/src/constants/tabs.tsx
> +];
これ最初やろうとしてたんだけど、ESLintに怒られるみたいなのでやめた
![image](https://github.com/NUTFes/NUTFES-Account/assets/46074208/ad9ed6fa-8147-497e-96ce-e9c698b8df72)

2023-06-26 16:30 UTC, TsubasaOura commented on frontend/src/components/common/SideTab.tsx
> +          }}
iconとnameみたいな一番したの子要素は直で指定して良いといいうこと？

2023-06-26 16:32 UTC, TsubasaOura commented on frontend/src/components/common/SideTab.tsx
> +              }}
これが一番下の子要素

2023-06-26 16:32 UTC, TsubasaOura commented on frontend/src/components/common/SideTab.tsx
> +              }}
一番したの子要素

2023-06-26 16:38 UTC, TsubasaOura commented on frontend/src/components/common/SideTab.tsx
> +              }}
一番下は指定していいなら問題なさそうだけど、
指定しない方がよければ現状微妙にサイドバーが縮む問題が発生してしまう


Uploading 画面収録 2023-06-27 午前1.21.45.mov…

2023-06-26 16:39 UTC, TsubasaOura commented on frontend/src/components/common/SideTab.tsx
> +              }}
一番下は指定していいなら問題なさそうだけど、
指定しない方がよければ現状微妙にサイドバーが縮む問題が発生してしまう

https://github.com/NUTFes/NUTFES-Account/assets/46074208/2d6719fa-72fb-4629-8f67-05c316f1fdfa

2023-06-26 17:58 UTC, imaimai17468 commented on frontend/src/constants/tabs.tsx
> +];
僕の環境だとESLintのエラーも出ずちゃんと型推論されるんですが、エラーが出るなら`as const`は使わなくていいと思います
リロードしたら治りそう

2023-06-26 18:20 UTC, imaimai17468 requested changes

2023-06-26 18:20 UTC, imaimai17468 commented on frontend/src/components/layout/HomeLayout.tsx
> +      <aside className="hidden w-[280px] lg:block xl:block 2xl:block">
画面を狭めた時にSideTabが小さくなってしまうのはflex-shrinkを指定してないためです
これが初期値の場合は、画面幅に合わせて要素の幅を自動で調整しようとします

また、`w-[100px]`みたいな書き方はしないようにしましょう。これを許容すると、`p-[5px]`とか`color-[#hoeghoge]`みたいなのが増え続けて、やりたい放題tailwind祭りになってしまい、classNameが訳わからなくなります
これをやるならtailwindじゃなくcss modulesを採用するべきです

最後に、`lg:block xl:block 2xl:block`について、tailwindのレスポンシブデザインは、min-widthでメディアクエリを切り替えているので、`lg:block`の時点で、**lg以上の場合はblockにする**というcssが当たっています。
そのため、xlと2xlの指定は不要です。
xlのときはまたhiddenにするとかならアリです。
```suggestion
      <aside className="hidden w-72 shrink-0 lg:block">
```

2023-06-26 18:37 UTC, imaimai17468 commented on frontend/src/components/common/SideTab.tsx
> +              }}
@TsubasaOura 
縮む根本的な原因はwidthとheightを指定しているからではありません
https://github.com/NUTFes/NUTFES-Account/pull/85#discussion_r1242584562
を参考にしてください
shrinkを指定したら、widthを指定しなくても縮まなくなります。

widthとheightを指定して無理やり固定しているだけです
それどころか、画像に示したようにwidth:220pxにした影響で、cssくんが空気を読んで`220にしたいの〜？無理だよ〜`と縮めていますし、heightに関しては、本来のフォントにかかっているline-heightを無視して無理やり20pxにしていることがわかると思います。
また、文字についてはheightではなくfont-sizeで調整したいです

別にwidhtとheightを指定することを悪と言っているわけではなくて、画像で示した通り、本来当てたかったcsvが噛み合わずに齟齬が出る可能性を考慮する必要があるということです。

<img width="360" alt="スクリーンショット 2023-06-27 3 28 51" src="https://github.com/NUTFes/NUTFES-Account/assets/52590941/512df1ac-01b9-4860-9bc7-f891b93dea65">

2023-06-26 18:39 UTC, imaimai17468 commented on frontend/src/components/common/SideTab.tsx
> +          }}
<img>や<p>、<div>みたいなプリミティブな要素については直で指定するのはアリです
今回はコンポーネントなのでグレーです

2023-06-26 18:56 UTC, imaimai17468 requested changes
追加でレビューしました

2023-06-26 18:56 UTC, imaimai17468 commented on frontend/src/components/common/SideTab.tsx
> +            <ListItemIcon style={{ minWidth: "40px" }} sx={{ pr: "16px" }}>
`<ListItemIcon>`に関しては、コンポーネント自体がmin-widthでスタイリングしてるので、それを上書きするのはアリです
ただ、全体を40pxにして、そのうち右側16pxをpaddingとするのは少しわかりづらいので、IconはIconの幅に合わせつつ、gapで間隔を取るのはどうでしょうか？
[note] sxの共通部分をまとめることができたので共有します
参考：https://mui.com/system/getting-started/the-sx-prop/#array-values
```suggestion
          <ListItemButton
            onClick={() => handleClick(tab.href || "#")}
            sx={[
              {
                gap: "1rem",
                py: "10px",
                pr: "16px",
                pl: "24px",
                borderTopRightRadius: 25,
                borderBottomRightRadius: 25,
              },
              router.pathname === tab.href
                ? {
                    backgroundColor: "#E8F0FE",
                    color: "#1967D2",
                    "& .MuiListItemIcon-root": {
                      color: "#1967D2",
                    },
                    "&:hover": {
                      backgroundColor: "#E8F0FE",
                    },
                  }
                : {
                    color: "text.secondary",
                  },
            ]}
          >
            <ListItemIcon style={{ minWidth: "fit-content" }}>{tab.icon}</ListItemIcon>
```

2023-06-26 18:58 UTC, imaimai17468 commented on frontend/src/components/common/SideTab.tsx
> +            <ListItemIcon style={{ minWidth: "40px" }} sx={{ pr: "16px" }}>
@TsubasaOura 
本家見たら、全体40pxでpadding-rightを取ってたので、現状のままで大丈夫そうです！すみません
sx propsの共有部分のとこだけ参考にしてもらえたらなと

2023-06-29 02:16 UTC, TsubasaOura commented on frontend/src/constants/tabs.tsx
> +];
リロードしたら治った....

2023-06-29 02:20 UTC, TsubasaOura commented on frontend/src/components/common/SideTab.tsx
> +              }}
理解的

2023-06-29 02:20 UTC, TsubasaOura commented on frontend/src/components/common/SideTab.tsx
> +            <ListItemIcon style={{ minWidth: "40px" }} sx={{ pr: "16px" }}>
承知！

2023-06-30 01:57 UTC, imaimai17468 approved these changes
LGTM!

2023-06-30 01:57 UTC, merged