birthdayPageの作成
NUTFes/NUTFES-Account pull request #89
Opened 2023-07-03 15:14 UTC by ryuseifujisaki

## 対応 Issue

resolve #87 

## 概要

## birthdayページの作成を行いました。
[MUI Date Picker](https://mui.com/x/react-date-pickers/date-picker/)を利用して実装しました。

## なぜData Pickerを利用したか？
[Date Calendar](https://mui.com/x/react-date-pickers/date-calendar/)を公式通り実装したが、どうしてもHydration Errorが消す事ができなかったため、Data Pickerを利用した。
Hydration Errorを消せるなら、Date Calendarを利用するのが良さそう

## 今後実装するもの
- 誕生日を保存する機能の実装
現時点では、保存ボタンを押すと、カレンダーで選択した日をコンソールに出力する処理になっています。
APIが存在するなら実装するので、言ってください。🙇

- 登録してある誕生日の取得機能の実装
現時点は2022年4月17日で定義しています。

## テスト項目

- [ ] 誕生日を選択することができ、コンソールに出力されるか
- [ ] デザイン面について
- [ ] コード面について

## URL・スクリーンショット

- http://localhost:3000/birthday
- 実装した画面
![image](https://github.com/NUTFes/NUTFES-Account/assets/50622120/370fd20f-0288-4ec7-9cd6-74b20403f3ed)

## 備考
正直Data Pickerのみだとダサいので、なんとかしたいところ

2023-07-04 01:53 UTC, TsubasaOura commented
- date-calender使えそう
- https://zenn.dev/longbridge/articles/e6f0d6ac0a3559 これ使って日本語化だけお願いしたい
- 保存ボタンは色付きでPrimaryボタンな雰囲気を出したい
- 保存・キャンセルボタンはカードの右下揃えで配置したい

2023-07-05 06:05 UTC, TsubasaOura requested changes
https://github.com/NUTFes/NUTFES-Account/pull/89#issuecomment-1619348264

2023-07-11 10:11 UTC, ryuseifujisaki commented
コメントされたものは基本的に修正したので確認お願いします。🙇

2023-07-11 10:43 UTC, TsubasaOura requested changes
Rebaseでほしいとこが消されてしまってそう

2023-07-11 10:43 UTC, TsubasaOura commented on frontend/package.json
> -    "start": "next start -p 12345",
同様

2023-07-11 10:43 UTC, TsubasaOura commented on frontend/package.json
> -    "dev": "next dev -p 12345",
これ消したら動かなそう

2023-07-11 10:43 UTC, TsubasaOura commented on frontend/src/pages/birthday.tsx
> -  const details = DETAIL_PAGE_CONSTANTS.birthday;
ここで詳細取ってこれるようにしてる！

2023-07-11 10:43 UTC, TsubasaOura commented on frontend/src/pages/birthday.tsx
> -    <DetailLayout {...details}>
ここで詳細を適応してます！

2023-07-11 10:43 UTC, TsubasaOura commented on frontend/src/pages/birthday.tsx
> +  };
constansに移行したので削除でおけ！

2023-07-11 15:35 UTC, TsubasaOura commented on frontend/src/pages/birthday.tsx
> -import { DETAIL_PAGE_CONSTANTS } from "@/constants/detailPage";
使います！

2023-07-11 15:35 UTC, TsubasaOura commented on frontend/src/pages/birthday.tsx
> +              position: "absolute",
absoluteは親要素とか無視して
「絶対ここに配置」
みたいな挙動になるから良くないかも

2023-07-11 15:35 UTC, TsubasaOura commented on frontend/src/pages/birthday.tsx
> +        <div className="h-screen w-full items-center justify-center">
ここでh-screenを使用するとdetailLayoutのカード全体がPCの画面の縦幅になるから
ヘッダーとかを合わせるとPCの画面以上の縦幅になり
余計なスクロールが発生してしまう

2023-07-11 15:35 UTC, TsubasaOura commented on frontend/src/pages/birthday.tsx
> +import ja from "date-fns/locale/ja";
```suggestion
import { ja } from "date-fns/locale";
```
の方がいいらしい

2023-07-12 00:27 UTC, ryuseifujisaki commented on frontend/src/pages/birthday.tsx
> -  const details = DETAIL_PAGE_CONSTANTS.birthday;
理解

2023-07-12 00:27 UTC, ryuseifujisaki commented on frontend/src/pages/birthday.tsx
> +  };
理解

2023-07-12 00:27 UTC, ryuseifujisaki commented on frontend/src/pages/birthday.tsx
> +import ja from "date-fns/locale/ja";
ライブラリが追加する可能性があるからかな？

2023-07-12 00:27 UTC, ryuseifujisaki commented on frontend/package.json
> -    "start": "next start -p 12345",
理解

2023-07-12 00:27 UTC, ryuseifujisaki commented on frontend/package.json
> -    "dev": "next dev -p 12345",
理解

2023-07-12 00:36 UTC, ryuseifujisaki commented on frontend/src/pages/birthday.tsx
> +              position: "absolute",
relativeとabsolute完全に理解した
https://qiita.com/ChiJ_SeaW/items/b18b2dc98443ab988ecb

2023-07-12 02:22 UTC, TsubasaOura commented on frontend/src/pages/birthday.tsx
> +import ja from "date-fns/locale/ja";
これはちょっとなんでかわからない

2023-07-12 02:22 UTC, TsubasaOura commented on frontend/src/pages/birthday.tsx
> +import ja from "date-fns/locale/ja";
型定義ファイルが
 "date-fns/locale"
にあるから？

2023-07-12 03:25 UTC, ryuseifujisaki commented on frontend/src/pages/birthday.tsx
> +        <div className="h-screen w-full items-center justify-center">
`h-auto`で中の要素に合わせるように設定

2023-07-12 03:26 UTC, ryuseifujisaki commented on frontend/src/pages/birthday.tsx
> +              position: "absolute",
relativeにして、親要素のbottomから40px離れた場所に設定

2023-07-12 04:42 UTC, TsubasaOura approved these changes

2023-07-12 04:42 UTC, TsubasaOura commented on frontend/src/pages/birthday.tsx
> -    <DetailLayout {...details}>
動くので今回はマージします！
が、
{...details}
のスプレッド構文って書き方魅力的なので
目を通しておくとよき
https://qiita.com/Yametaro/items/814f40d08e9d30584e20#props%E3%81%AF%E3%82%B9%E3%83%97%E3%83%AC%E3%83%83%E3%83%89%E6%A7%8B%E6%96%87%E3%81%A7%E6%B8%A1%E3%81%9B%E3%82%8B

2023-07-12 04:43 UTC, merged